[package]
name = "pulse_tutorial_test"
version = "0.1.0"
edition = "2021"

[lints.rust]
unused = "allow"
non_camel_case_types = "allow"
non_snake_case = "allow"
non_upper_case_globals = "allow"


[lib]
path = "voting.rs"
test = true